# Generated by Django 5.2.7 on 2025-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://www.shutterstock.com/image-illustration/coming-soon-concept-image-text-600nw-2402613961.jpg', max_length=500),
        ),
    ]
